# This workflow will create a pypi package and upload it with twine

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install
    - name: Upload
      run: |
        env:
          pipy_token: ${{ secrets.PYPI_TOKEN }}

        echo "hello world"
        pip install yolk3k
        pip install twine
        pip install keyring==21.4.0
        cd ci
        python upload_package.py
